// Town names in every language the products speak — shared, byte-identical,
// between the app (lib/cityNames.ts) and the website (src/lib/cityNames.ts).
//
// The keys are the Hebrew names of the town table (CITY_COORDS). Each product's
// dictionary had its own `cities` map, and they covered barely 80 of about 200
// towns: in English, Afula, Kiryat Shmona or Modi'in showed in Hebrew, and
// "Afula" typed in the search found nothing. The dictionaries now start from
// this table (their own names still win), and the search matches a town by its
// name in any of these languages, whatever language the screen is in.
//
// Abbreviations in the town table (תא, פת, ראשלצ…) carry the full town's names.

export type CityLang = 'en' | 'ru' | 'ar' | 'fr' | 'hi' | 'uk';

export const CITY_NAMES: Record<string, Partial<Record<CityLang, string>>> = {
  'תל אביב': { en: 'Tel Aviv', ru: 'Тель-Авив', ar: 'تل أبيب', fr: 'Tel Aviv', hi: 'तेल अवीव', uk: 'Тель-Авів' },
  'חיפה': { en: 'Haifa', ru: 'Хайфа', ar: 'حيفا', fr: 'Haifa', hi: 'हाइफ़ा', uk: 'Хайфа' },
  'ירושלים': { en: 'Jerusalem', ru: 'Иерусалим', ar: 'القدس', fr: 'Jérusalem', hi: 'येरुशलम', uk: 'Єрусалим' },
  'באר שבע': { en: 'Beer Sheva', ru: 'Беэр-Шева', ar: 'بئر السبع', fr: 'Beer Sheva', hi: 'बेएर शेवा', uk: 'Беер-Шева' },
  'נתניה': { en: 'Netanya', ru: 'Нетания', ar: 'نتانيا', fr: 'Netanya', hi: 'नेतान्या', uk: 'Нетанія' },
  'ראשון לציון': { en: 'Rishon LeZion', ru: 'Ришон-ле-Цион', ar: 'ريشون لتسيون', fr: 'Rishon LeZion', hi: 'रिशोन लेज़ियोन', uk: 'Рішон-ле-Ціон' },
  'אשדוד': { en: 'Ashdod', ru: 'Ашдод', ar: 'أشدود', fr: 'Ashdod', hi: 'अशदोद', uk: 'Ашдод' },
  'אשקלון': { en: 'Ashkelon', ru: 'Ашкелон', ar: 'عسقلان', fr: 'Ashkelon', hi: 'अश्केलोन', uk: 'Ашкелон' },
  'פתח תקוה': { en: 'Petah Tikva', ru: 'Петах-Тиква', ar: 'بتاح تكفا', fr: 'Petah Tikva', hi: 'पेताह तिकवा', uk: 'Петах-Тіква' },
  'כפר סבא': { en: 'Kfar Saba', ru: 'Кфар-Саба', ar: 'كفار سابا', fr: 'Kfar Saba', hi: 'कफ़र साबा', uk: 'Кфар-Саба' },
  'פרדסיה': { en: 'Pardesiya', ru: 'Пардесия', ar: 'برديسيا', fr: 'Pardessiya', hi: 'परदेसिया', uk: 'Пардесія' },
  'רעננה': { en: 'Raanana', ru: 'Раанана', ar: 'رعنانا', fr: 'Raanana', hi: 'रानाना', uk: 'Раанана' },
  'הרצליה': { en: 'Herzliya', ru: 'Герцлия', ar: 'هرتسليا', fr: 'Herzliya', hi: 'हर्ज़लिया', uk: 'Герцлія' },
  'נצרת': { en: 'Nazareth', ru: 'Назарет', ar: 'الناصرة', fr: 'Nazareth', hi: 'नाज़रेथ', uk: 'Назарет' },
  'טבריה': { en: 'Tiberias', ru: 'Тверия', ar: 'طبريا', fr: 'Tibériade', hi: 'तबेरिया', uk: 'Тіверія' },
  'אילת': { en: 'Eilat', ru: 'Эйлат', ar: 'إيلات', fr: 'Eilat', hi: 'एलात', uk: 'Ейлат' },
  'עכו': { en: 'Acre', ru: 'Акко', ar: 'عكا', fr: 'Acre', hi: 'अक्को', uk: 'Акко' },
  'חריש': { en: 'Harish', ru: 'Хариш', ar: 'حريش', fr: 'Harish', hi: 'हरीश', uk: 'Хариш' },
  'רחובות': { en: 'Rehovot', ru: 'Реховот', ar: 'رحوفوت', fr: 'Rehovot', hi: 'रेहोवोत', uk: 'Реховот' },
  'בת ים': { en: 'Bat Yam', ru: 'Бат-Ям', ar: 'بات يام', fr: 'Bat Yam', hi: 'बत याम', uk: 'Бат-Ям' },
  'רמת גן': { en: 'Ramat Gan', ru: 'Рамат-Ган', ar: 'رمات غان', fr: 'Ramat Gan', hi: 'रामत गन', uk: 'Рамат-Ган' },
  'הוד השרון': { en: 'Hod HaSharon', ru: 'Ход-ха-Шарон', ar: 'هود هشارون', fr: 'Hod HaSharon', hi: 'होद हाशारोन', uk: 'Ход-га-Шарон' },
  'עפולה': { en: 'Afula', ru: 'Афула', ar: 'العفولة', fr: 'Afula', hi: 'अफुला', uk: 'Афула' },
  'קריית שמונה': { en: 'Kiryat Shmona', ru: 'Кирьят-Шмона', ar: 'قرية شمونة', fr: 'Kiryat Shmona', hi: 'किर्यात श्मोना', uk: 'Кір\'ят-Шмона' },
  'מודיעין': { en: 'Modi\'in', ru: 'Модиин', ar: 'موديعين', fr: 'Modi\'in', hi: 'मोदिइन', uk: 'Модіїн' },
  'מודיעין עילית': { en: 'Modiin Illit', ru: 'Модиин-Иллит', ar: 'موديعين عيليت', fr: 'Modiin Illit', hi: 'मोदिइन इलित', uk: 'Модіїн-Іліт' },
  'לוד': { en: 'Lod', ru: 'Лод', ar: 'اللد', fr: 'Lod', hi: 'लोद', uk: 'Лод' },
  'רמלה': { en: 'Ramle', ru: 'Рамла', ar: 'الرملة', fr: 'Ramla', hi: 'रामले', uk: 'Рамла' },
  'גבעת שמואל': { en: 'Giv\'at Shmuel', ru: 'Гиват-Шмуэль', ar: 'جفعات شموئيل', fr: 'Givat Shmuel', hi: 'गिवात शमूएल', uk: 'Гіват-Шмуель' },
  'בני ברק': { en: 'Bnei Brak', ru: 'Бней-Брак', ar: 'بني براك', fr: 'Bnei Brak', hi: 'बने ब्राक', uk: 'Бней-Брак' },
  'גבעתיים': { en: 'Givatayim', ru: 'Гиватаим', ar: 'جبعاتيم', fr: 'Givatayim', hi: 'गिवातायिम', uk: 'Гіватаїм' },
  'חולון': { en: 'Holon', ru: 'Холон', ar: 'حولون', fr: 'Holon', hi: 'होलोन', uk: 'Холон' },
  'אור יהודה': { en: 'Or Yehuda', ru: 'Ор-Иехуда', ar: 'أور يهودا', fr: 'Or Yehuda', hi: 'ओर यहूदा', uk: 'Ор-Єгуда' },
  'יבנה': { en: 'Yavne', ru: 'Явне', ar: 'يبنه', fr: 'Yavne', hi: 'यावने', uk: 'Явне' },
  'קריית אתא': { en: 'Kiryat Ata', ru: 'Кирьят-Ата', ar: 'كريات آتا', fr: 'Kiryat Ata', hi: 'किर्यात अता', uk: 'Кір\'ят-Ата' },
  'קריית גת': { en: 'Kiryat Gat', ru: 'Кирьят-Гат', ar: 'كريات جات', fr: 'Kiryat Gat', hi: 'किर्यात गत', uk: 'Кір\'ят-Гат' },
  'קריית מלאכי': { en: 'Kiryat Malakhi', ru: 'Кирьят-Малахи', ar: 'كريات ملاخي', fr: 'Kiryat Malakhi', hi: 'किर्यात मलाखी', uk: 'Кір\'ят-Малахі' },
  'קריית ביאליק': { en: 'Kiryat Bialik', ru: 'Кирьят-Биалик', ar: 'كريات بياليك', fr: 'Kiryat Bialik', hi: 'किर्यात बियालिक', uk: 'Кір\'ят-Бялик' },
  'קריית מוצקין': { en: 'Kiryat Motzkin', ru: 'Кирьят-Моцкин', ar: 'كريات موتسكين', fr: 'Kiryat Motzkin', hi: 'किर्यात मोत्ज़किन', uk: 'Кір\'ят-Моцкін' },
  'קריית ים': { en: 'Kiryat Yam', ru: 'Кирьят-Ям', ar: 'كريات يام', fr: 'Kiryat Yam', hi: 'किर्यात याम', uk: 'Кір\'ят-Ям' },
  'נהריה': { en: 'Nahariya', ru: 'Нагария', ar: 'نهاريا', fr: 'Nahariya', hi: 'नहरिया', uk: 'Нагарія' },
  'נצרת עילית': { en: 'Nof HaGalil', ru: 'Ноф-ха-Галиль', ar: 'نوف هاغليل', fr: 'Nof HaGalil', hi: 'नोफ़ हागलील', uk: 'Ноф-га-Галіль' },
  'ראש העין': { en: 'Rosh HaAyin', ru: 'Рош-ха-Аин', ar: 'روش هعين', fr: 'Rosh HaAyin', hi: 'रोश हाइन', uk: 'Рош-га-Аїн' },
  'אלעד': { en: 'Elad', ru: 'Элад', ar: 'إلعاد', fr: 'Elad', hi: 'एलाद', uk: 'Елад' },
  'יהוד': { en: 'Yehud-Monosson', ru: 'Иегуд-Моноссон', ar: 'يهود موناسون', fr: 'Yehud-Monosson', hi: 'येहुद-मोनोसोन', uk: 'Єгуд-Моносон' },
  'מזכרת בתיה': { en: 'Mazkeret Batya', ru: 'Мазкерет-Батья', ar: 'مزكيرت باتيا', fr: 'Mazkeret Batya', hi: 'मज़केरेत बतिया', uk: 'Мазкерет-Батья' },
  'גדרה': { en: 'Gedera', ru: 'Гедера', ar: 'غيديرا', fr: 'Gedera', hi: 'गेदेरा', uk: 'Гедера' },
  'נס ציונה': { en: 'Nes Ziona', ru: 'Нес-Циона', ar: 'نيس تسيونا', fr: 'Nes Ziona', hi: 'नेस ज़ियोना', uk: 'Нес-Ціона' },
  'ראשל"צ': { en: 'Rishon LeZion', ru: 'Ришон-ле-Цион', ar: 'ريشون لتسيون', fr: 'Rishon LeZion', hi: 'रिशोन लेज़ियोन', uk: 'Рішон-ле-Ціон' },
  'ת"א': { en: 'Tel Aviv', ru: 'Тель-Авив', ar: 'تل أبيب', fr: 'Tel Aviv', hi: 'तेल अवीव', uk: 'Тель-Авів' },
  'פ"ת': { en: 'Petah Tikva', ru: 'Петах-Тиква', ar: 'بتاح تكفا', fr: 'Petah Tikva', hi: 'पेताह तिकवा', uk: 'Петах-Тіква' },
  'ר"ג': { en: 'Ramat Gan', ru: 'Рамат-Ган', ar: 'رمات غان', fr: 'Ramat Gan', hi: 'रामत गन', uk: 'Рамат-Ган' },
  'ב"ב': { en: 'Bnei Brak', ru: 'Бней-Брак', ar: 'بني براك', fr: 'Bnei Brak', hi: 'बने ब्राक', uk: 'Бней-Брак' },
  'כ"ס': { en: 'Kfar Saba', ru: 'Кфар-Саба', ar: 'كفار سابا', fr: 'Kfar Saba', hi: 'कफ़र साबा', uk: 'Кфар-Саба' },
  'טירת כרמל': { en: 'Tirat Carmel', ru: 'Тират-Кармель', ar: 'طيرة الكرمل', fr: 'Tirat Carmel', hi: 'तिरात कर्मेल', uk: 'Тірат-Кармель' },
  'דלית אל כרמל': { en: 'Daliyat al-Karmel', ru: 'Далият-эль-Кармель', ar: 'دالية الكرمل', fr: 'Daliyat al-Karmel', hi: 'दलियत अल-कर्मेल', uk: 'Даліят-ель-Кармель' },
  'עמק יזרעאל': { en: 'Jezreel Valley', ru: 'Изреельская долина', ar: 'مرج ابن عامر', fr: 'Vallée de Jezreel', hi: 'यिज्रेल घाटी', uk: 'Ізреельська долина' },
  'בית שמש': { en: 'Beit Shemesh', ru: 'Бейт-Шемеш', ar: 'بيت شيمش', fr: 'Beit Shemesh', hi: 'बेत शेमेश', uk: 'Бейт-Шемеш' },
  'מעלה אדומים': { en: 'Maale Adumim', ru: 'Маале-Адумим', ar: 'معالي أدوميم', fr: 'Maale Adumim', hi: 'माले अदुमिम', uk: 'Маале-Адумім' },
  'אריאל': { en: 'Ariel', ru: 'Ариэль', ar: 'أريئيل', fr: 'Ariel', hi: 'एरियल', uk: 'Аріель' },
  'זכרון יעקב': { en: 'Zichron Yaakov', ru: 'Зихрон-Яаков', ar: 'زخرون يعكوف', fr: 'Zichron Yaakov', hi: 'ज़िक्रोन याकोव', uk: 'Зіхрон-Яаков' },
  'פרדס חנה': { en: 'Pardes Hanna', ru: 'Пардес-Хана', ar: 'برديس حنا', fr: 'Pardès Hanna', hi: 'परदेस हन्ना', uk: 'Пардес-Хана' },
  'מגדל העמק': { en: 'Migdal HaEmek', ru: 'Мигдаль-ха-Эмек', ar: 'مجدل هعيمق', fr: 'Migdal HaEmek', hi: 'मिगदल हाएमेक', uk: 'Мігдаль-га-Емек' },
  'שדרות': { en: 'Sderot', ru: 'Сдерот', ar: 'سديروت', fr: 'Sderot', hi: 'सदेरोत', uk: 'Сдерот' },
  'נתיבות': { en: 'Netivot', ru: 'Нетивот', ar: 'نتيفوت', fr: 'Netivot', hi: 'नेतीवोत', uk: 'Нетівот' },
  'דימונה': { en: 'Dimona', ru: 'Димона', ar: 'ديمونا', fr: 'Dimona', hi: 'दिमोना', uk: 'Дімона' },
  'ערד': { en: 'Arad', ru: 'Арад', ar: 'عراد', fr: 'Arad', hi: 'अराद', uk: 'Арад' },
  'מצפה רמון': { en: 'Mitzpe Ramon', ru: 'Мицпе-Рамон', ar: 'متسبي رامون', fr: 'Mitzpe Ramon', hi: 'मित्ज़पे रामोन', uk: 'Міцпе-Рамон' },
  'אופקים': { en: 'Ofakim', ru: 'Офаким', ar: 'أوفاكيم', fr: 'Ofakim', hi: 'ओफ़ाकिम', uk: 'Офакім' },
  'נשר': { en: 'Nesher', ru: 'Нешер', ar: 'نيشر', fr: 'Nesher', hi: 'नेशर', uk: 'Нешер' },
  'נוף הגליל': { en: 'Nof HaGalil', ru: 'Ноф-ха-Галиль', ar: 'نوف هاغليل', fr: 'Nof HaGalil', hi: 'नोफ़ हागलील', uk: 'Ноф-га-Галіль' },
  'שפרעם': { en: 'Shfaram', ru: 'Шфарам', ar: 'شفاعمرو', fr: 'Shfaram', hi: 'शफ़रआम', uk: 'Шфарам' },
  'צפת': { en: 'Safed', ru: 'Цфат', ar: 'صفد', fr: 'Safed', hi: 'सफ़ेद', uk: 'Цфат' },
  'בית שאן': { en: 'Beit Shean', ru: 'Бейт-Шеан', ar: 'بيسان', fr: 'Beit Shean', hi: 'बेत शान', uk: 'Бейт-Шеан' },
  'יוקנעם': { en: 'Yokneam', ru: 'Йокнеам', ar: 'يوكنعام', fr: 'Yokneam', hi: 'योकनेम', uk: 'Йокнеам' },
  'סח\'נין': { en: 'Sakhnin', ru: 'Сахнин', ar: 'سخنين', fr: 'Sakhnine', hi: 'सखनीन', uk: 'Сахнін' },
  'טמרה': { en: 'Tamra', ru: 'Тамра', ar: 'طمرة', fr: 'Tamra', hi: 'तमरा', uk: 'Тамра' },
  'אום אל-פחם': { en: 'Umm al-Fahm', ru: 'Умм эль-Фахм', ar: 'أم الفحم', fr: 'Oum el-Fahm', hi: 'उम्म अल-फ़हम', uk: 'Умм-ель-Фахм' },
  'מג\'ד אל-כרום': { en: 'Majd al-Krum', ru: 'Мадж-аль-Крум', ar: 'مجد الكروم', fr: 'Majd al-Krum', hi: 'मज्द अल-करूम', uk: 'Мадж-ель-Крум' },
  'באקה אל-גרביה': { en: 'Baqa al-Gharbiyye', ru: 'Бака-эль-Гарбийя', ar: 'باقة الغربية', fr: 'Baqa al-Gharbiyye', hi: 'बाका अल-गरबिया', uk: 'Бака-ель-Гарбія' },
  'כפר קאסם': { en: 'Kafr Qasim', ru: 'Кафр-Касем', ar: 'كفر قاسم', fr: 'Kafr Qasim', hi: 'काफ़र कासेम', uk: 'Кфар-Касем' },
  'קלנסווה': { en: 'Kalansua', ru: 'Калансуа', ar: 'قلنسوة', fr: 'Kalansua', hi: 'कलानसुआ', uk: 'Калансаве' },
  'טייבה': { en: 'Tayibe', ru: 'Тайба', ar: 'الطيبة', fr: 'Tayibe', hi: 'तायबे', uk: 'Тайібе' },
  'אור עקיבא': { en: 'Or Akiva', ru: 'Ор-Акива', ar: 'أور عكيفا', fr: 'Or Akiva', hi: 'ओर अकीवा', uk: 'Ор-Аківа' },
  'פרדס חנה-כרכור': { en: 'Pardes Hanna-Karkur', ru: 'Пардес-Ханна-Каркур', ar: 'برديس حنا-كركور', fr: 'Pardes Hanna-Karkur', hi: 'परदेस हाना-कार्कुर', uk: 'Пардес-Хана-Каркур' },
  'חדרה': { en: 'Hadera', ru: 'Хадера', ar: 'حديرة', fr: 'Hadera', hi: 'हदेरा', uk: 'Хадера' },
  'כפר יונה': { en: 'Kfar Yona', ru: 'Кфар-Йона', ar: 'كفار يونا', fr: 'Kfar Yona', hi: 'कफ़र योना', uk: 'Кфар-Йона' },
  'קדימה-צורן': { en: 'Kadima-Zoran', ru: 'Кадима-Цорен', ar: 'كديما-تسوران', fr: 'Kadima-Zoran', hi: 'कदीमा-ज़ोरेन', uk: 'Кадіма-Цоран' },
  'רמת השרון': { en: 'Ramat HaSharon', ru: 'Рамат-ха-Шарон', ar: 'رمات هشارون', fr: 'Ramat HaSharon', hi: 'रामत हाशारोन', uk: 'Рамат-га-Шарон' },
  'יהוד-מונוסון': { en: 'Yehud-Monosson', ru: 'Иегуд-Моноссон', ar: 'يهود موناسون', fr: 'Yehud-Monosson', hi: 'येहुद-मोनोसोन', uk: 'Єгуд-Моносон' },
  'גני תקווה': { en: 'Ganei Tikva', ru: 'Гней-Тиква', ar: 'غاني تكفا', fr: 'Ganei Tikva', hi: 'गने तिकवा', uk: 'Ганей-Тіква' },
  'שוהם': { en: 'Shoham', ru: 'Шохам', ar: 'شوهام', fr: 'Shoham', hi: 'शोहाम', uk: 'Шогам' },
  'אזור': { en: 'Azor', ru: 'Азур', ar: 'أزور', fr: 'Azor', hi: 'अज़ोर', uk: 'Азор' },
  'מבשרת ציון': { en: 'Mevaseret Zion', ru: 'Мевасерет-Цион', ar: 'مفاسيريت صيون', fr: 'Mevaseret Zion', hi: 'मेवासेरेत ज़ियोन', uk: 'Мевасерет-Ціон' },
  'גבעת זאב': { en: 'Givat Zeev', ru: 'Гиват-Зеев', ar: 'غفعات زئيف', fr: 'Givat Zeev', hi: 'गिवात ज़ेएव', uk: 'Гіват-Зеев' },
  'ביתר עלית': { en: 'Beitar Illit', ru: 'Бейтар-Иллит', ar: 'بيتار عيليت', fr: 'Beitar Illit', hi: 'बेतार इलित', uk: 'Бейтар-Іліт' },
  'מודיעין עלית': { en: 'Modiin Illit', ru: 'Модиин-Иллит', ar: 'موديعين عيليت', fr: 'Modiin Illit', hi: 'मोदिइन इलित', uk: 'Модіїн-Іліт' },
  'רהט': { en: 'Rahat', ru: 'Рахат', ar: 'رهط', fr: 'Rahat', hi: 'रहत', uk: 'Рахат' },
  'ירוחם': { en: 'Yeruham', ru: 'Йерухам', ar: 'يروحام', fr: 'Yeruham', hi: 'येरुहाम', uk: 'Єрухам' },
  'כרמיאל': { en: 'Carmiel', ru: 'Кармиэль', ar: 'كرميئيل', fr: 'Carmiel', hi: 'कर्मिएल', uk: 'Кармієль' },
  'מעלות תרשיחא': { en: 'Ma\'alot-Tarshiha', ru: 'Маалот-Таршиха', ar: 'معالوت ترشيحا', fr: 'Maalot-Tarshiha', hi: 'मालोत-तरशीहा', uk: 'Маалот-Таршиха' },
  'סחנין': { en: 'Sakhnin', ru: 'Сахнин', ar: 'سخنين', fr: 'Sakhnin', hi: 'साखनिन', uk: 'Сахнін' },
  'עראבה': { en: 'Arraba', ru: 'Арраба', ar: 'عرابة', fr: 'Arraba', hi: 'अर्राबा', uk: 'Арраба' },
  'מגאר': { en: 'Maghar', ru: 'Мгар', ar: 'المغار', fr: 'Maghar', hi: 'मगर', uk: 'Мгар' },
  'ירכא': { en: 'Yarka', ru: 'Ярка', ar: 'يركا', fr: 'Yarka', hi: 'यरका', uk: 'Ярка' },
  'כפר יאסיף': { en: 'Kafr Yasif', ru: 'Кафр-Ясиф', ar: 'كفر ياسيف', fr: 'Kafr Yasif', hi: 'कफ़्र यासिफ़', uk: 'Кафр-Ясіф' },
  'כאבול': { en: 'Kabul', ru: 'Кабуль', ar: 'كابول', fr: 'Kaboul', hi: 'काबुल', uk: 'Кабуль' },
  'כפר מנדא': { en: 'Kafr Manda', ru: 'Кафр-Манда', ar: 'كفر مندا', fr: 'Kafr Manda', hi: 'कफ़्र मंदा', uk: 'Кафр-Манда' },
  'ריינה': { en: 'Reineh', ru: 'Рейне', ar: 'الرينة', fr: 'Reineh', hi: 'रेइने', uk: 'Рейне' },
  'יפיע': { en: 'Yafa an-Naseriyye', ru: 'Яфа-ан-Насирия', ar: 'يافة الناصرة', fr: 'Yafa an-Naseriyye', hi: 'याफ़ा अन-नासिरिया', uk: 'Яфа-ан-Насірія' },
  'אכסאל': { en: 'Iksal', ru: 'Иксаль', ar: 'إكسال', fr: 'Iksal', hi: 'इक्साल', uk: 'Іксаль' },
  'דאלית אל-כרמל': { en: 'Daliyat al-Karmel', ru: 'Далият-эль-Кармель', ar: 'دالية الكرمل', fr: 'Daliyat al-Karmel', hi: 'दलियत अल-कर्मेल', uk: 'Даліят-ель-Кармель' },
  'עוספיא': { en: 'Isfiya', ru: 'Исфия', ar: 'عسفيا', fr: 'Isfiya', hi: 'इस्फ़िया', uk: 'Ісфія' },
  'קצרין': { en: 'Katzrin', ru: 'Кацрин', ar: 'كتسرين', fr: 'Katzrin', hi: 'कात्ज़रिन', uk: 'Кацрин' },
  'מטולה': { en: 'Metula', ru: 'Метула', ar: 'المطلة', fr: 'Metoula', hi: 'मेटुला', uk: 'Метула' },
  'ראש פינה': { en: 'Rosh Pinna', ru: 'Рош-Пина', ar: 'روش بينا', fr: 'Rosh Pina', hi: 'रोश पिना', uk: 'Рош-Піна' },
  'יקנעם עילית': { en: 'Yokneam Illit', ru: 'Йокнеам-Илит', ar: 'يوكنعام عيليت', fr: 'Yokneam Illit', hi: 'योकनीम इलित', uk: 'Йокнеам-Іліт' },
  'בנימינה': { en: 'Binyamina', ru: 'Биньямина', ar: 'بنيامينا', fr: 'Binyamina', hi: 'बिन्यामिना', uk: 'Біньяміна' },
  'אבן יהודה': { en: 'Even Yehuda', ru: 'Эвен-Иегуда', ar: 'إيفن يهودا', fr: 'Even Yehouda', hi: 'इवन यहूदा', uk: 'Евен-Єгуда' },
  'תל מונד': { en: 'Tel Mond', ru: 'Тель-Монд', ar: 'تل موند', fr: 'Tel Mond', hi: 'तेल मोंड', uk: 'Тель-Монд' },
  'גן יבנה': { en: 'Gan Yavne', ru: 'Ган-Явне', ar: 'جان يفنه', fr: 'Gan Yavne', hi: 'गान यावने', uk: 'Ган-Явне' },
  'קרית עקרון': { en: 'Kiryat Ekron', ru: 'Кирьят-Экрон', ar: 'كريات عكرون', fr: 'Kiryat Ekron', hi: 'किर्यात एक्रोन', uk: 'Кір\'ят-Екрон' },
  'טירה': { en: 'Tira', ru: 'Тира', ar: 'الطيرة', fr: 'Tira', hi: 'तीरा', uk: 'Тіра' },
  'ג\'לג\'וליה': { en: 'Jaljulia', ru: 'Джальджулия', ar: 'جلجولية', fr: 'Jaljulia', hi: 'जलजुलिया', uk: 'Джальджулія' },
  'בית ג\'ן': { en: 'Beit Jann', ru: 'Бейт-Джан', ar: 'بيت جن', fr: 'Beit Jann', hi: 'बेत जान', uk: 'Бейт-Джан' },
  'ג\'דיידה-מכר': { en: 'Judeida-Makr', ru: 'Джудейда-Макр', ar: 'الجديدة المكر', fr: 'Judeida-Makr', hi: 'जुदैदा-मक्र', uk: 'Джудейда-Макр' },
  'אבו סנאן': { en: 'Abu Snan', ru: 'Абу-Снан', ar: 'أبو سنان', fr: 'Abu Snan', hi: 'अबू सनान', uk: 'Абу-Снан' },
  'מיתר': { en: 'Meitar', ru: 'Меитар', ar: 'ميتار', fr: 'Meitar', hi: 'मेतार', uk: 'Меітар' },
  'להבים': { en: 'Lehavim', ru: 'Лехавим', ar: 'لهافيم', fr: 'Lehavim', hi: 'लेहाविम', uk: 'Легавім' },
  'עומר': { en: 'Omer', ru: 'Омер', ar: 'عومر', fr: 'Omer', hi: 'ओमर', uk: 'Омер' },
  'כסייפה': { en: 'Kuseife', ru: 'Кусейфе', ar: 'كسيفة', fr: 'Kseifa', hi: 'कुसैफ़े', uk: 'Кусейфе' },
  'שגב שלום': { en: 'Segev Shalom', ru: 'Сегев-Шалом', ar: 'شقيب السلام', fr: 'Segev Shalom', hi: 'सेगेव शालोम', uk: 'Сегев-Шалом' },
  'חורה': { en: 'Hura', ru: 'Хура', ar: 'حورة', fr: 'Hura', hi: 'हूरा', uk: 'Хура' },
  'כפר ורדים': { en: 'Kfar Vradim', ru: 'Кфар-Врадим', ar: 'كفار فراديم', fr: 'Kfar Vradim', hi: 'कफ़र व्रादिम', uk: 'Кфар-Врадім' },
  'שלומי': { en: 'Shlomi', ru: 'Шломи', ar: 'شلومي', fr: 'Shlomi', hi: 'श्लोमी', uk: 'Шломі' },
  'מעיליא': { en: 'Mi\'ilya', ru: 'Милия', ar: 'معليا', fr: 'Mi\'ilya', hi: 'मिइलिया', uk: 'Мілія' },
  'פקיעין': { en: 'Peki\'in', ru: 'Пкиин', ar: 'البقيعة', fr: 'Peki\'in', hi: 'पेकीइन', uk: 'Пкіїн' },
  'קרית אונו': { en: 'Kiryat Ono', ru: 'Кирьят-Оно', ar: 'قرية أونو', fr: 'Kiryat Ono', hi: 'किर्यात ओनो', uk: 'Кір\'ят-Оно' },
  'קריית אונו': { en: 'Kiryat Ono', ru: 'Кирьят-Оно', ar: 'قرية أونو', fr: 'Kiryat Ono', hi: 'किर्यात ओनो', uk: 'Кір\'ят-Оно' },
  'באר יעקב': { en: 'Be\'er Ya\'akov', ru: 'Беэр-Яаков', ar: 'بئير يعقوب', fr: 'Beer Yaakov', hi: 'बीर याकोव', uk: 'Беер-Яаков' },
  'בית דגן': { en: 'Beit Dagan', ru: 'Бейт-Даган', ar: 'بيت داغان', fr: 'Beit Dagan', hi: 'बेत दागान', uk: 'Бейт-Даган' },
  'סביון': { en: 'Savyon', ru: 'Савьон', ar: 'سافيون', fr: 'Savyon', hi: 'सव्योन', uk: 'Савйон' },
  'כפר שמריהו': { en: 'Kfar Shmaryahu', ru: 'Кфар-Шмарьяху', ar: 'كفار شمرياهو', fr: 'Kfar Shmaryahou', hi: 'कफ़र श्मर्याहू', uk: 'Кфар-Шмарягу' },
  'כוכב יאיר': { en: 'Kochav Yair', ru: 'Кохав-Яир', ar: 'كوخاف يائير', fr: 'Kokhav Yaïr', hi: 'कोखव यायर', uk: 'Кохав-Яїр' },
  'צור יגאל': { en: 'Tzur Yigal', ru: 'Цур-Игаль', ar: 'تسور يغآل', fr: 'Tzour Yigal', hi: 'त्ज़ूर यिगाल', uk: 'Цур-Ігаль' },
  'אלפי מנשה': { en: 'Alfei Menashe', ru: 'Альфей-Менаше', ar: 'ألفي منشيه', fr: 'Alfei Menashe', hi: 'अल्फ़ेई मनश्शे', uk: 'Альфей-Менаше' },
  'אורנית': { en: 'Oranit', ru: 'Оранит', ar: 'أورانيت', fr: 'Oranit', hi: 'ओरानित', uk: 'Оранит' },
  'אלקנה': { en: 'Elkana', ru: 'Элькана', ar: 'إلكانا', fr: 'Elkana', hi: 'एल्काना', uk: 'Елькана' },
  'שערי תקווה': { en: 'Sha\'arei Tikva', ru: 'Шаарей-Тиква', ar: 'شعاري تكفا', fr: 'Shaarei Tikva', hi: 'शारेई तिक्वा', uk: 'Шаарей-Тіква' },
  'קרני שומרון': { en: 'Karnei Shomron', ru: 'Карней-Шомрон', ar: 'كرني شومرون', fr: 'Karnei Shomron', hi: 'कर्नेई शोमरोन', uk: 'Карней-Шомрон' },
  'עמנואל': { en: 'Immanuel', ru: 'Иммануэль', ar: 'عمانوئيل', fr: 'Emmanuel', hi: 'इमानुएल', uk: 'Іммануель' },
  'קדומים': { en: 'Kedumim', ru: 'Кдумим', ar: 'كدوميم', fr: 'Kedoumim', hi: 'केदुमिम', uk: 'Кдумім' },
  'בית אריה': { en: 'Beit Aryeh', ru: 'Бейт-Арье', ar: 'بيت أرييه', fr: 'Beit Arié', hi: 'बेत आर्ये', uk: 'Бейт-Ар\'є' },
  'קיסריה': { en: 'Caesarea', ru: 'Кейсария', ar: 'قيسارية', fr: 'Césarée', hi: 'सीज़ेरिया', uk: 'Кесарія' },
  'עתלית': { en: 'Atlit', ru: 'Атлит', ar: 'عتليت', fr: 'Atlit', hi: 'अत्लित', uk: 'Атліт' },
  'גבעת עדה': { en: 'Giv\'at Ada', ru: 'Гиват-Ада', ar: 'جفعات عادا', fr: 'Givat Ada', hi: 'गिवात अदा', uk: 'Гіват-Ада' },
  'בני עייש': { en: 'Bnei Ayish', ru: 'Бней-Аиш', ar: 'بني عايش', fr: 'Bnei Ayish', hi: 'ब्नेई आयिश', uk: 'Бней-Аїш' },
  'באר טוביה': { en: 'Be\'er Tuvia', ru: 'Беэр-Тувия', ar: 'بئير طوفيا', fr: 'Beer Touvia', hi: 'बीर तुविया', uk: 'Беер-Тувія' },
  'תל שבע': { en: 'Tel Sheva', ru: 'Тель-Шева', ar: 'تل السبع', fr: 'Tel Sheva', hi: 'तेल शेवा', uk: 'Тель-Шева' },
  'לקיה': { en: 'Lakiya', ru: 'Лакия', ar: 'اللقية', fr: 'Lakiya', hi: 'लकिया', uk: 'Лакія' },
  'ערערה בנגב': { en: 'Ar\'arat an-Naqab', ru: 'Арара-ба-Негев', ar: 'عرعرة النقب', fr: 'Ar\'ara-BaNegev', hi: 'अरारा बनेगेव', uk: 'Арара-ба-Негев' },
  'שדה בוקר': { en: 'Sde Boker', ru: 'Сде-Бокер', ar: 'سديه بوكير', fr: 'Sde Boker', hi: 'स्देह बोकेर', uk: 'Сде-Бокер' },
  'אבו גוש': { en: 'Abu Ghosh', ru: 'Абу-Гош', ar: 'أبو غوش', fr: 'Abu Ghosh', hi: 'अबू गोश', uk: 'Абу-Гош' },
  'אפרת': { en: 'Efrat', ru: 'Эфрат', ar: 'إفرات', fr: 'Efrat', hi: 'एफ़्रात', uk: 'Ефрат' },
  'קרית ארבע': { en: 'Kiryat Arba', ru: 'Кирьят-Арба', ar: 'كريات أربع', fr: 'Kiryat Arba', hi: 'किर्यात अरबा', uk: 'Кір\'ят-Арба' },
  'בית אל': { en: 'Beit El', ru: 'Бейт-Эль', ar: 'بيت إيل', fr: 'Beit El', hi: 'बेत एल', uk: 'Бейт-Ель' },
  'כוכב יעקב': { en: 'Kochav Ya\'akov', ru: 'Кохав-Яаков', ar: 'كوخاف يعقوب', fr: 'Kokhav Yaakov', hi: 'कोखव याकोव', uk: 'Кохав-Яаков' },
  'צור הדסה': { en: 'Tzur Hadassah', ru: 'Цур-Хадаса', ar: 'تسور هداسا', fr: 'Tzour Hadassah', hi: 'त्ज़ूर हदस्सा', uk: 'Цур-Гадаса' },
  'תקוע': { en: 'Tekoa', ru: 'Текоа', ar: 'تقوع', fr: 'Tekoa', hi: 'तकोआ', uk: 'Текоа' },
  'קרית טבעון': { en: 'Kiryat Tiv\'on', ru: 'Кирьят-Тивон', ar: 'كريات طبعون', fr: 'Kiryat Tivon', hi: 'किर्यात तिवोन', uk: 'Кір\'ят-Тівон' },
  'קריית טבעון': { en: 'Kiryat Tiv\'on', ru: 'Кирьят-Тивон', ar: 'كريات طبعون', fr: 'Kiryat Tivon', hi: 'किर्यात तिवोन', uk: 'Кір\'ят-Тівон' },
  'רמת ישי': { en: 'Ramat Yishai', ru: 'Рамат-Ишай', ar: 'رمات يشاي', fr: 'Ramat Yishai', hi: 'रमात यिशाई', uk: 'Рамат-Ішай' },
  'כפר תבור': { en: 'Kfar Tavor', ru: 'Кфар-Тавор', ar: 'كفار تافور', fr: 'Kfar Tavor', hi: 'कफ़र तावोर', uk: 'Кфар-Тавор' },
  'יבנאל': { en: 'Yavne\'el', ru: 'Явниэль', ar: 'يفنيئيل', fr: 'Yavnéel', hi: 'यवनेल', uk: 'Явніель' },
  'כפר כמא': { en: 'Kafr Kama', ru: 'Кфар-Кама', ar: 'كفر كما', fr: 'Kfar Kama', hi: 'कफ़र कामा', uk: 'Кфар-Кама' },
  'כפר כנא': { en: 'Kafr Kanna', ru: 'Кафр-Кана', ar: 'كفر كنا', fr: 'Kafr Kanna', hi: 'कफ़्र काना', uk: 'Кафр-Кана' },
  'עילוט': { en: 'Ilut', ru: 'Илут', ar: 'عيلوط', fr: 'Ilout', hi: 'इलूत', uk: 'Ілут' },
  'משהד': { en: 'Mashhad', ru: 'Машхад', ar: 'المشهد', fr: 'Mashhad', hi: 'मशहद', uk: 'Машхад' },
  'דבוריה': { en: 'Daburiyya', ru: 'Дабурия', ar: 'دبورية', fr: 'Daburiyya', hi: 'दबूरिया', uk: 'Дабурія' },
  'עין מאהל': { en: 'Ein Mahil', ru: 'Эйн-Махиль', ar: 'عين ماهل', fr: 'Ein Mahil', hi: 'ऐन माहिल', uk: 'Ейн-Махіль' },
  'בסמת טבעון': { en: 'Basmat Tab\'un', ru: 'Басмат-Табун', ar: 'بسمة طبعون', fr: 'Basmat Tab\'un', hi: 'बसमत ताबुन', uk: 'Басмат-Табун' },
  'זרזיר': { en: 'Zarzir', ru: 'Зарзир', ar: 'زرزير', fr: 'Zarzir', hi: 'ज़रज़ीर', uk: 'Зарзір' },
  'ביר אל-מכסור': { en: 'Bir al-Maksur', ru: 'Бир-эль-Максур', ar: 'بير المكسور', fr: 'Bir al-Maksur', hi: 'बीर अल-मकसूर', uk: 'Бір-ель-Максур' },
  'אעבלין': { en: 'I\'billin', ru: 'Ибиллин', ar: 'عبلين', fr: 'Ibillin', hi: 'इबिल्लिन', uk: 'Ібіллін' },
  'שעב': { en: 'Sha\'ab', ru: 'Шааб', ar: 'شعب', fr: 'Sha\'ab', hi: 'शाब', uk: 'Шааб' },
  'טורעאן': { en: 'Tur\'an', ru: 'Туран', ar: 'طرعان', fr: 'Tur\'an', hi: 'तुरआन', uk: 'Туран' },
  'חצור הגלילית': { en: 'Hatzor HaGlilit', ru: 'Хацор-ха-Глилит', ar: 'حتسور هجليليت', fr: 'Hatzor HaGlilit', hi: 'हत्ज़ोर हगलीलित', uk: 'Хацор-га-Гліліт' },
  'מגדל': { en: 'Migdal', ru: 'Мигдаль', ar: 'مجدال', fr: 'Migdal', hi: 'मिगदल', uk: 'Мігдаль' },
  'טובא-זנגריה': { en: 'Tuba-Zangariyye', ru: 'Туба-Зангария', ar: 'طوبا الزنغرية', fr: 'Tuba-Zangariyye', hi: 'तूबा-ज़ंगरिया', uk: 'Туба-Зангарія' },
  'יסוד המעלה': { en: 'Yesud HaMa\'ala', ru: 'Есуд-ха-Маала', ar: 'يسود همعلاه', fr: 'Yesud HaMaala', hi: 'यसूद हमाला', uk: 'Єсуд-га-Маала' },
  'חורפיש': { en: 'Hurfeish', ru: 'Хурфейш', ar: 'حرفيش', fr: 'Hurfeish', hi: 'हुर्फ़ेश', uk: 'Хурфейш' },
  'ראמה': { en: 'Rameh', ru: 'Рама', ar: 'الرامة', fr: 'Rameh', hi: 'रामा', uk: 'Рама' },
  'דיר חנא': { en: 'Deir Hanna', ru: 'Дейр-Ханна', ar: 'دير حنا', fr: 'Deir Hanna', hi: 'देर हन्ना', uk: 'Дейр-Ханна' },
  'נחף': { en: 'Nahf', ru: 'Нахф', ar: 'نحف', fr: 'Nahf', hi: 'नहफ़', uk: 'Нахф' },
  'דיר אל-אסד': { en: 'Deir al-Asad', ru: 'Дейр-эль-Асад', ar: 'دير الأسد', fr: 'Deir al-Asad', hi: 'देर अल-असद', uk: 'Дейр-ель-Асад' },
  'בענה': { en: 'Bi\'ina', ru: 'Биина', ar: 'البعنة', fr: 'Bi\'ina', hi: 'बीना', uk: 'Біїна' },
  'ג\'וליס': { en: 'Julis', ru: 'Джулис', ar: 'جولس', fr: 'Julis', hi: 'जूलिस', uk: 'Джуліс' },
  'כסרא-סמיע': { en: 'Kisra-Sumei', ru: 'Кисра-Сумей', ar: 'كسرى سميع', fr: 'Kisra-Sumei', hi: 'किसरा-सुमेई', uk: 'Кісра-Сумей' },
  'סאג\'ור': { en: 'Sajur', ru: 'Саджур', ar: 'ساجور', fr: 'Sajur', hi: 'साजूर', uk: 'Саджур' },
  'מסעדה': { en: 'Mas\'ade', ru: 'Масаде', ar: 'مسعدة', fr: 'Mas\'ade', hi: 'मसादे', uk: 'Масаде' },
  'מג\'דל שמס': { en: 'Majdal Shams', ru: 'Мадждаль-Шамс', ar: 'مجدل شمس', fr: 'Majdal Shams', hi: 'मजदल शम्स', uk: 'Мадждаль-Шамс' },
  'בוקעאתא': { en: 'Buq\'ata', ru: 'Букаата', ar: 'بقعاثا', fr: 'Buq\'ata', hi: 'बुकाता', uk: 'Букаата' },
  'ג\'סר א-זרקא': { en: 'Jisr az-Zarqa', ru: 'Джиср-эз-Зарка', ar: 'جسر الزرقاء', fr: 'Jisr az-Zarqa', hi: 'जिस्र अज़-ज़रका', uk: 'Джиср-ез-Зарка' },
  'כפר קרע': { en: 'Kafr Qara', ru: 'Кафр-Кара', ar: 'كفر قرع', fr: 'Kafr Qara', hi: 'कफ़्र क़रा', uk: 'Кафр-Кара' },
  'ערערה': { en: 'Ar\'ara', ru: 'Арара', ar: 'عرعرة', fr: 'Ar\'ara', hi: 'अरारा', uk: 'Арара' },
  'זמר': { en: 'Zemer', ru: 'Земер', ar: 'زيمر', fr: 'Zemer', hi: 'ज़ेमेर', uk: 'Земер' },
  'כפר ברא': { en: 'Kafr Bara', ru: 'Кафр-Бара', ar: 'كفر برا', fr: 'Kafr Bara', hi: 'कफ़्र बरा', uk: 'Кафр-Бара' },
  'קלנסוואה': { en: 'Qalansawe', ru: 'Калансуа', ar: 'قلنسوة', fr: 'Qalansawe', hi: 'क़लनसवा', uk: 'Калансуа' },
};

/** Hebrew town → its name in `lang`, for every town that has one. */
export function cityNamesFor(lang: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [city, names] of Object.entries(CITY_NAMES)) {
    const n = names[lang as CityLang];
    if (n) out[city] = n;
  }
  return out;
}

/** Every name a town goes by, Hebrew first. */
export function allCityNames(city: string): string[] {
  return [city, ...Object.values(CITY_NAMES[city] ?? {})];
}
